---
title: "Correlation techniques for digital time-of-flight measurement by airborne ultrasonic rangefinders"
author: Angelo M. Sabatini, Enrico Spinielli
date: "1994-09-16"
doi: https://doi.org/10.1109/IROS.1994.407566
---

## Abstract

Ultrasonic pulse-echo ranging systems based on threshold detection methods are popular devices in the robotic field, as a means for determining the proximity of objects in a cost-effective manner. Despite their widespread use, serious concerns are often raised regarding the accuracy of the sensed data, particularly when the return signals are received at low signal-to-noise ratios. In principle, correlation-based detection methods provide better performance for their outstanding capability of detecting and recovering weak signals buried in noise, so as to permit ranging at longer distances, or, the distance being the same, at higher frequencies, with resulting improvements in spatial resolution in spite of the increased attenuation. In this paper the authors describe a simple pulse-echo ranging system whose receiver signal processing is completely digital: the use of appropriate sampling techniques and signal processing algorithms allows one to benefit from the advantages of correlation-based detection methods for accurate ranging of multiple objects, without compromising the most prominent features of pulse-echo sonar systems, namely their relatively low cost and simplicity of operation. The experimental results presented concern the use of relatively high-frequency ultrasonic transducers.

## Venue

International Conference on Intelligent Robots and Systems (IROS'94), 12-16 September 1994, Munich, Germany.