---
author: "Enrico Spinielli"
blogger_id: "tag:blogger.com,1999:blog-1947405997418753543.post-287329049599051800"
blogger_orig_url: "https://ongiantsshoulders.blogspot.com/2009/06/scons-and-noweb.html"
date: "2009-06-14"
categories: ["LaTeX", "Python", "Literate Programming"]
title: "Scons and noweb"
license: CC BY-SA
---

I was curious to see how I could integrate noweb and Scons.

You can download my little Sconstruct for this,
[Sconstruct.example](https://enrico.spinielli.googlepages.com/Sconstruct.example).
It defines two builders. NoWeave is used to produce TeX or LaTeX documents,
while NoTangle extracts the non-document artefacts, i.e. programs, config files,
scripts ... It also includes productions for generating a sample program about
Ackermann function: 


{{< highlight python "style=emacs" >}}
	ackdoc  = env.NoWeave('ack.tex', 'ack.nw')
	ackcode = env.NoTangle('ack.py', 'ack.nw')
	acktest = env.NoTangle('ackTest.py', 'ack.nw')
{{< / highlight >}}


The noweb source is [ack.nw](https://enrico.spinielli.googlepages.com/ack.nw) and
the companion BibTeX file is
[ack.bib](https://enrico.spinielli.googlepages.com/ack.bib)

It contains the doc chunks describing the function, the source code chunck for
the relevant Python code and the code chunk for the unit test.

You can try it out executing


{{< highlight bash >}}
	$ scons -f Sconstruct.example
{{< / highlight >}}


You will get the following artefacts,
[ack.py](https://enrico.spinielli.googlepages.com/ack.py),
[ack.tex](https://enrico.spinielli.googlepages.com/ack.tex),
[ackTest.py](https://enrico.spinielli.googlepages.com/ackTest.py) and
[ack.pdf](https://enrico.spinielli.googlepages.com/ack.pdf) 

Remember to run BibTeX first...
