---
author: "Enrico Spinielli"
blogger_id: "tag:blogger.com,1999:blog-1947405997418753543.post-1883437193742052867"
blogger_orig_url: "https://ongiantsshoulders.blogspot.com/2009/02/my-giants.html"
date: "2009-02-23"
categories: ["LaTeX", "Croquet", "Literate Programming"]
title: "My Giants"
license: CC BY-SA
---

I am probably too selective, anyway my models for computer science/software engineering (one of them would disagree on both definitions) are just two: [Donald E. Knuth](https://www-cs-faculty.stanford.edu/~uno/) and [Alan Kay](https://www.vpri.org/html/people/founders.htm).

The first one continues to surprise me with the depth, clarity and joy of his works: from TeX (well, I use LaTex but it does not exist without TeX) to The Art of Computer Programming to Literate Programming.

About the latter, I was one of the blessed to be present to [his Turing Award Lecture](https://awards.acm.org/citation.cfm?id=3972189&amp;srt=year&amp;year=2003&amp;aw=140&amp;ao=AMTURING): he shocked me to the point I had two sleepless nights so angry I was about having wasted so much time in useless (computer) matters! After that I have been studying and using a lot of what he wrote and presented from Squeak to Croquet to the Burroughs B5000 and stack computers to his recent line of [exploration](https://www.vpri.org/html/work/ifnct.htm) and the proposal to NSF about [reinventing programming (PDF)](https://www.vpri.org/pdf/rn2006002_nsfprop.pdf).